FROM node:18-alpine AS build_stage

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# STAGE 2: Serve with Nginx
FROM nginx:stable-alpine AS production-stage
# Copy the built files from the first stage to Nginx's hosting folder
COPY --from=build_stage /app/build /usr/share/nginx/html
# Copy your custom configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]